### DISCUSSION TITLE
Inverters 2+

### DISCUSSION THREAD

**Discussion by PL4STER** [hultenvp/solis-sensor#119] [Q&A]
Hello. And how to set two or more inverters because it duplicates the first inverter with the standard setting: /

**Comment by hultenvp** [comment]
Hi,

2 options:
If both inverters are in the same plantId then the integration will detect both inverters automatically and offer all available sensors.
I only have one inverter myself, so if this is your configuration and it isn't working then create an issue with clear debugging logs so I can find the cause and fix it.

Other one is that you have 2 different plantIds each with one inverter. In that case you just add another config to the configuration.yaml, one for each plantID:
```
sensor:
  - platform: solis
    name: "My Solis Inverter#1"
    portal_domain: "m.ginlong.com" (replace for Solarman, Sofar)
    portal_username: "portal_username"
    portal_password: "portal_password"
    portal_plant_id: "plantId#1"
sensor:
  - platform: solis
    name: "My Solis Inverter #2"
    portal_domain: "m.ginlong.com" (replace for Solarman, Sofar)
    portal_username: "portal_username"
    portal_password: "portal_password"
    portal_plant_id: "plantId#2"
```
