### DISCUSSION TITLE
configuration.yaml example? cannot add this device via UI

### DISCUSSION THREAD

**Discussion by juggler11** [hultenvp/solis-sensor#336] [General]
Hi. When i try to add the solis integration i got "This device cannot be added from the UI. You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information." I have run the testscript and that works like a charm but how can i add this manually in de configuration.yaml file?

something like?

```
sensor:
  - platform: solis
    name: "My Solis Inverter"
    plant_ids: "19digitvalue"
    secretKey: "123456"
    KeyId: "123456789"
```
