### ISSUE TITLE
Ha can't restart after updates. 

### ISSUE THREAD

**Issue by lex53** [hultenvp/solis-sensor#117]
Hi,

I'm getting this error and cannot restart.
Any ideas?

Logger: homeassistant.config
Source: config.py:454
First occurred: 10:09:31 PM (1 occurrences)
Last logged: 10:09:31 PM

Invalid config for [sensor.solis]: [inverter_serial] is an invalid option for [sensor.solis]. Check: sensor.solis->inverter_serial. (See /config/sensors.yaml, line 1). Please check the docs at https://github.com/hultenvp/solis-sensor/

**Comment by hultenvp** [comment]
Hi @lex53,

You have a [very old config](https://github.com/hultenvp/solis-sensor#ginlong-platform-v2)
inverter_serial is no longer a valid config entry. The integration now autodetects all inverters present in a plant and reports their data fields as sensors.
It has been deprecated for a while and the log produced warnings that the inverter serial was deprecated, so I guess you either skipped a few updates or missed the warnings.
Just remove inverter_serial and your integration will work again.

Cheers.

**Comment by lex53** [comment]
Hi thanks for the quick response.

I removed inverter_serial from sensors. Yaml file but it's still not
rebooting. Is that the correct file or should I be looking somewhere else?

Cheers
Alex

**Comment by hultenvp** [comment]
Hey Alex

You need to remove it from the configuration.Yaml file.
I assume your sensors.yaml  is included from your configuration.yaml. if so, then that should be fine otherwise edit your configuration.yaml.

As per documentation the config should look as follows:
```
sensor:
  - platform: solis
    name: "My Solis Inverter"
    portal_domain: "m.ginlong.com" (replace for Solarman, Sofar)
    portal_username: "portal_username"
    portal_password: "portal_password"
    portal_plant_id: "plantId"
```

Home assistant can sometimes be hard to convince that the config has changed, but after a reboot it must for sure accept the config.

If still not working then please post the log.
