### ISSUE TITLE
The plugin stopped reporting at 5th of august

### ISSUE THREAD

**Issue by DdenBraver** [hultenvp/solis-sensor#133]
The plugin stopped reporting for me on the 5th of august at 13:00 CET.
I tried to reinstall the plugin, and re-enter my configuration but nothing seems to help, it remains "Unavailable"
Restarting HA, or even rebooting the VM HA is running at did not resolve the issue.

I am using the SolisCloud integration.

Configuration looks like:

```
# Solis / Ginseng Inverter
sensor:
  - platform: solis
    name: "Solis"
    portal_domain: "www.soliscloud.com:13333"
    portal_username: "username"
    portal_key_id: "13003863816********"
    portal_secret: "9fd02b******`47c59a5a64c3d4******"
    portal_plant_id: "1298491919448******"
```

Does anybody else have this issue?

![image](https://user-images.githubusercontent.com/12996032/183283770-6868561c-d4e7-4567-afc2-f1dc299a4f4c.png)
![image](https://user-images.githubusercontent.com/12996032/183284049-99d3d225-d384-4c51-994b-4771431e1fe0.png)
![image](https://user-images.githubusercontent.com/12996032/183284394-eaad149b-852e-4fb0-814b-c047e6f21c29.png)

_Originally posted by @DdenBraver in https://github.com/hultenvp/solis-sensor/issues/105#issuecomment-1207364116_
