### ISSUE TITLE
Soliscloud API support

### ISSUE THREAD

**Issue by hawkeye100** [hultenvp/solis-sensor#18]
As far as I can tell, I have followed the instructions - files downloaded and put in the correct place on my HA install including the config in configuration.yaml. Checked via File Editor as well as Samba share.
HA is 2021.10.6 on Virtualbox vdi. [Other changes on HA are OK including adding integrations from UI].

When I check the config, I get the following:
 
> Platform error sensor.solis - Integration 'solis' not found.

The full log shows:

> File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
> await hass.services.async_call(
> File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
> task.result()
> File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
> await handler.job.target(service_call)
> File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 585, in async_handle_core_service
> raise HomeAssistantError(
> homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.solis - Integration 'solis' not found.

I am afraid this does not mean much to me as a HA newbie (and rusty programmer).

I  have created a new account in m.ginlong.com and checked it logs on OK to web interface. Those credentials are in the config. (this is because Solis moved my main account to soliscloud.com recently)

Any help (in layman's terms) would be much appreciated. Thanks

**Comment by hultenvp** [comment]
Hi @hawkeye100,

It looks like HA cannot find the solis integration.
Please (double) check the following:
- ensure you have a directories 'custom_components/solis' in the same directory as your configuration.yaml (case sensitive)
- make  sure the following latest files are in the solis directory
- [ ] manifest.json (should show v 0.2.2 if you read it)
- [ ] const.py 
- [ ] platform2_portal (version 0.0.5)
- [ ] sensor.py  (version 0.2.2)

Your configuration.yaml should have a block like this, use "check configuration" in your config menu to check if it's correct:
```
  - platform: solis
    name: "Solis"
    portal_domain: "m.ginlong.com"
    portal_username: "your_user_name" 
    portal_password: "your password"
    portal_plant_id: "your_plant_id"
    inverter_serial: "your_inverter_serial"
    sensors:
      temperature:
      dcinputvoltagepv1:
      dcinputcurrentpv1:
      acoutputvoltage3:
      acoutputcurrent3:
      actualpower:
      energylastmonth:
      energytoday:
      energythismonth:
      energythisyear:
      energytotal:
```

If that all doesn't help then please provide a anonymized copy of your configuration.yaml and your custom_components layout.
