### ISSUE TITLE
Battery wrong data

### ISSUE THREAD

**Issue by kisjeth** [hultenvp/solis-sensor#259]
from tonight the battery reports unrealistic data, with charge values ​​of 55000kwh but no charge anomaly appears on the application.
![Screenshot_2023-02-14-09-05-37-072-edit_io homeassistant companion android](https://user-images.githubusercontent.com/91030699/218676845-c0f768dc-807e-46e5-a74b-e0c9366f4dcd.jpg)

V.3.3.1

**Comment by alienatedsec** [comment]
Check #258

**Comment by barthoefs** [comment]
Same issue here.
The api in HA shows charging at 208,745.0 and the soliscloud app shows 2087.

**Comment by kisjeth** [comment]
> Same issue here. The api in HA shows charging at 208,745.0 and the soliscloud app shows 2087.

I create a sensor and change like #258 suggested

**Comment by barthoefs** [comment]
> > Same issue here. The api in HA shows charging at 208,745.0 and the soliscloud app shows 2087.
> 
> I create a sensor and change like #258 suggested

Can you show your code please?

**Comment by viking2010** [comment]
Hope this helps. Place this in your config.yaml file. I have mine separated so have a templates.yaml file where I stick this. 

```
  - sensor:
    - name: New Battery Power
      unit_of_measurement: kW
      device_class: power
      state: >
        {% set new_battery_power = states('sensor.solis_inverter_battery_power') | float(0) / 100 %} 
        {{ new_battery_power }}
```

**Comment by kisjeth** [comment]
> > > Same issue here. The api in HA shows charging at 208,745.0 and the soliscloud app shows 2087.
> > 
> > 
> > I create a sensor and change like #258 suggested
> 
> Can you show your code please?

  - sensor:
      - name: "Carica/Scarica batteria corretto"
        unit_of_measurement: "W"
        state: "{{ (states('sensor.solis_battery_power_2') | float / 100) | round(3) }}"

**Comment by viking2010** [comment]
That's even better @kisjeth!

**Comment by YanisKyr** [comment]
Am I being dumb? Probably.. Any help would be much appreciated:

https://i.imgur.com/EYWUefq.png

**Comment by kisjeth** [comment]
> Am I being dumb? Probably.. Any help would be much appreciated:
> 
> ![What a mess](https://camo.githubusercontent.com/b5e8508e189314e0cf9c414e712e82cbaa1ceb40ce99301c1b5fce54161542a9/68747470733a2f2f692e696d6775722e636f6d2f455957556566712e706e67)

you have to create a sensor that reads data with the wrong measurement and transforms them with the correct unit of measurement.
to do this, you need to insert the above code into the configuration.yaml to create a new entity for it

`- sensor:
      - name: "CORRECT SENSOR"
        unit_of_measurement: "W"
        entity_id: "CHARGE/DISCHARGE"
        state: {{ (states('sensor.WRONG_SENSOR') | float / 100) | round(3) }}"`

**Comment by kisjeth** [comment]
> Am I being dumb? Probably.. Any help would be much appreciated:
> 
> ![What a mess](https://camo.githubusercontent.com/b5e8508e189314e0cf9c414e712e82cbaa1ceb40ce99301c1b5fce54161542a9/68747470733a2f2f692e696d6775722e636f6d2f455957556566712e706e67)

you have to create a sensor that reads data with the wrong measurement and transforms them with the correct unit of measurement.
to do this, you need to insert the above code into the configuration.yaml to create a new entity for it

```
- sensor:
     - name: "CORRECT SENSOR
        unit_of_measurement: "W"
        entity_id: "CHARGE/DISCHARGE"
        state: {{ (states('sensor.WRONG_SENSOR') | float / 100) | round(3) }}"
```

**Comment by YanisKyr** [comment]
For the record, what worked for me in the end is the below in the configuration.yaml

```
template:
  - sensor:
      - name: "Battery Temp FIX"
        unit_of_measurement: "W"
        state: "{{ (states('sensor.PROBLEMATIC_ONE') | float / 100) | round(2) }}"
```
