### ISSUE TITLE
not showing power

### ISSUE THREAD

**Issue by lex53** [hultenvp/solis-sensor#33]
Hi

Ive set this up in HA but no data is coming through. Do I need the quote marks with the user name and password or is it with out quotes in the configuration.yaml file?

also do i need to enter login details elsewhere?

cheers
alex

**Comment by hultenvp** [comment]
Hi Alex

Yes, domain, username, password, plant id, inverter serial are all in quote marks (")
Use the same credentials as you use to log in with m.ginlong.com

If that does not work please add the following to your configuration.yaml and please attach the log to this issue.


```
logger:
  default: warning
  logs:
    custom_components.solis: debug
```
