### ISSUE TITLE
No labels on solis setup box

### ISSUE THREAD

**Issue by GSV3MiaC** [hultenvp/solis-sensor#368]
**Describe the bug**

**Config**
Your anonymized config entry

**Versions**
HA Version an deployment
HACS version
Integration version

**Debug logs**
Add to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.solis: debug
```
And attach the resulting log to the issue. If yo do not know where to find logs you missed an important step in the install of HACS. ;-)

**Screenshots**
