### ISSUE TITLE
Refresh rate

### ISSUE THREAD

**Issue by radzik80** [hultenvp/solis-sensor#42]
Hello, 

I have some problems with updating data from ginlong. As I found in code there should be refresing every two minutes. In my case there is only updated at HA restart.

Any suggestions?

Regards

**Comment by hultenvp** [comment]
Hi @radzik80: The code compares the new value to the previous and only notifies HomeAssistant of a change if there is any.
In night and on dark days updates could be very infrequent.

If there is sun and you still do not see updates then add the following to your configuration.yaml and attach the log to this issue 

```
logger:
  default: warning
  logs:
    custom_components.solis: debug
```
