### ISSUE TITLE
'Solis Battery Discharged Today' does not have decimal precision

### ISSUE THREAD

**Issue by Skyline-ThomasGH** [hultenvp/solis-sensor#422]
**Describe the bug**
The 'Solis Battery Discharged Today' entity only increases with full integers, causing very inaccurate energy dashboard graphs. In the past, before I moved my HA instance and updated this integration to the latest version, I did have one digit decimal precision for this entity.

**Config**
(not sure what to put here)

**Versions**
HACS v2.0.5
SolisCloud portal itegration v3.9.0

**Debug logs**
Let me know if I should enable these.

**Screenshots**

![Image](https://github.com/user-attachments/assets/98d7bf7b-f107-47de-9cb1-37e754f42837)

**Comment by patduckless** [comment]
Checking the JSON returned from the API it seems that they are sending a float. However my current discharge appears to be a whole number. I will check again tomorrow. 
It may be that Solis send a whole number formated as a float.

**Comment by patduckless** [comment]
I have raised this with Solis.

**Comment by tabannis** [comment]
This appears to be related to the previous issue #354 and a change made to the API by the Solis cloud gods.

If it helps, the decimal precision data for charge /discharge does still seem to exist in the official app/API...

![Screenshot_20250312-083854.png](https://github.com/user-attachments/assets/f0446bb6-f043-47ff-8dd9-3a37cba666e6)

**Comment by hultenvp** [comment]
This is a fallout of a revert to using inverterDetail instead of inverterDetaillist as there the problem was that the phase metrics were missing.
I prefer to wait for Solis, we could consider  even reverting to the unsupported inveterDetail, but I honestly do not know what we can expect there in terms of regression if we do.

**Comment by patduckless** [comment]
> I have raised this with Solis.

Solis never came back to me on this. I chased up last week, with no reply.

**Comment by mkuthan** [comment]
> > I have raised this with Solis.
> 
> Solis never came back to me on this. I chased up last week, with no reply.

They didn't answer me either :(

As a workaround I use [integral](https://www.home-assistant.io/integrations/integration/) integration to calculate approximate energy based on power readings.

Create two sensors for power in and out:

```
- name: "Solar Battery Power In"
        unit_of_measurement: W
        device_class: power
        icon: mdi:battery-plus
        state: >
          {% set power = states('sensor.solis_battery_power') | int %}
          {{ power if power > 0 else 0 }}

      - name: Solar Battery Power Out
        unit_of_measurement: W
        device_class: power
        icon: mdi:battery-minus
        state: >
          {% set power = states('sensor.solis_battery_power') | int %}
          {{ -power if power < 0 else 0 }}
```

Two more to estimate the energy in and out:

```
sensor:
  - platform: integration
    source: sensor.solar_battery_power_in
    name: Solar Battery Energy In
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5
  - platform: integration
    source: sensor.solar_battery_power_out
    name: Solar Battery Energy Out
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5
```

Voila:

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/0f83145b-4aaa-44a4-bdeb-8914f0087795" />
