### ISSUE TITLE
Feature Request - Grid Feed in Limit

### ISSUE THREAD

**Issue by janusr** [hultenvp/solis-sensor#462]
Love this integration. :-D
Possibility to modify Feed In Limit would be of special interest as I sometimes have negative export price:

![Image](https://github.com/user-attachments/assets/9d62174c-50d8-4ce7-b754-41df2d7c91df)

**Comment by patduckless** [comment]
I think this is added by [#463](https://github.com/hultenvp/solis-sensor/pull/463) and released with v3.11.0

**Comment by janusr** [comment]
Not quite same result. I don't want to limit the inverter output, but the export to the grid. Internal power use fluctuates, so setting the limit on the inverter is not good.

**Comment by janusr** [comment]
Tested this, it seems to read the value but does not take the Hectowatt (factor 100) into account:
I think the odd reason is that it must be in 100w increments.
![Image](https://github.com/user-attachments/assets/62ea9fdf-93e0-4412-9837-0fb3e8b9fd74)

**Comment by patduckless** [comment]
Yes it is a pain. Home assistant doesn't have hectowatt as a unit.

**Comment by janusr** [comment]
Workaround: A helper and an Automation

Input Number Helper:
![Image](https://github.com/user-attachments/assets/f074efa3-2776-43f5-9997-6e9df6e53bf5)

Automation:
```
alias: Update Solis Feed Limit
description: Updates solis_feed_in_power_limit based on master input in watts
triggers:
  - trigger: state
    entity_id:
      - input_number.solar_current_feed_in_limit
conditions: []
actions:
  - target:
      entity_id: number.solis_feed_in_power_limit
    data:
      value: >
        {{ (states('input_number.solar_current_feed_in_limit') | float / 100) |
        round(0) }}
    action: number.set_value
    enabled: true
  - target:
      entity_id: number.solis_feed_in_power_limit
    data:
      value: "124"
    action: number.set_value
    enabled: false
mode: single
```
