### ISSUE TITLE
Today and Total production not updating

### ISSUE THREAD

**Issue by sheminasalam** [hultenvp/solis-sensor#66]
After the recent updates today and total are not updating in my Sofar solar inverter. These are marked as unknown.

**Comment by hultenvp** [comment]
Hi, I'll need some more info to find the cause.

Please post your configuration and log output as well as versions of the integration and home assistant

Thanks

**Comment by sheminasalam** [comment]
Hi, after trying to sort it out and failing I converted my setup to your own direct wifi logger method and uninstalled this integration. But I  am sharing the integration that I have been using.

```
  - platform: solis
    name: "Sofar Inverter"
    portal_domain: "home.solarman.cn"
    portal_username: "rth@gmail.com"
    portal_password: !secret sofar
    portal_plant_id: "1456096"
    inverter_serial: "SH1ES0****G092"
    sensors:
      actualpower:
      energytoday:
      status:
      temperature:
      dcinputvoltagepv1:
      dcinputcurrentpv1:
      acoutputvoltage1:
      acoutputcurrent1:
      energylastmonth:
      energythismonth:
      energythisyear:
      energytotal:
```

I tried the latest 1.0.4 integration with the latest HA. Even with the 1.0.0 integration, the sensor was only getting updated not regularly which was seen as gaps in the solar energy production graphs in the energy tab. Version 0.0.4 was working great for me.
